# 1 overlay — Harness merges: values.yaml + 1-values.yaml (+ platform Vault env).

environment: 1

env:
  ENVIRONMENT: 1
  GOOGLE_DOMAIN_NAME: 1.net
  AUDIT_CONTROL_3_CONFIG: /apps/config/audittool_config.yaml
  ACTIVATION_GROUP_SUFFIX: _ActivationGroup
  LOG_LEVEL: INFO
  SOURCE_CREDENTIALS_GCP: VAULT
  RUNNING_ENVIRONMENT: LIGHTSPEED
