imageRepo: LS_IMAGE_BASE
imageVersion: LS_IMAGE_TAG
lsPipelineName: LS_PIPELINE_NAME

appName: gcp-iam-audit-tool
environment: 1

job:
  name: audit-tool-job
  restartPolicy: OnFailure
  backoffLimit: 3
