apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Values.job.name }}
  labels:
    app: {{ $.Values.appName }}
    environment: {{ $.Values.environment }}
  annotations:
    "helm.sh/hook": post-install
spec:
  backoffLimit: {{ $.Values.job.backoffLimit }}
  template:
    metadata:
      labels:
        app: {{ $.Values.appName }}
        environment: {{ $.Values.environment }}
    spec:
      serviceAccountName: {{ $.Values.appName }}-sa
      restartPolicy: {{ $.Values.job.restartPolicy }}
      containers:
        - name: {{ $.Values.appName }}-{{ $.Values.environment }}
          image: {{ $.Values.imageRepo | default $.Values.lsImageBase }}:{{ $.Values.imageVersion | default $.Chart.AppVersion }}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
{{- if $.Values.job.command }}
          command:
{{- range $.Values.job.command }}
            - {{ . | quote }}
{{- end }}
{{- end }}
{{- if $.Values.env }}
          env:
{{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
{{- end }}
{{- end }}
